# If docker-machine still hangs on trying to connect to "default", try this:
# $ eval $(docker-machine env pickles)
# where "pickles" was the name of the custom docker-machine
# then resume with
# $ docker-compose up -d

mailcatcher:
  image: dbit/mailcatcher:0.5.12
  ports:
    - "1080:1080"
    - "25"
  environment:
    MAILCATCHER_SMTP_PORT: "25"

node:
  hostname: sandbox-domojs
  domainname: luxpickles.lu
  build: ./
  ports:
    - "8080:8080"
  volumes:
    - .:/usr/src/app/domojs
  links:
    - mailcatcher:smtp_server
  environment:
    MAILCATCHER_PORT: "25"
